# Generated by Django 5.2.3 on 2026-08-16 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('order_type', models.CharField(choices=[('PURCHASE_ORDER', 'Purchase Order (PO)'), ('RFQ', 'Request for Quotation (RFQ)')], default='PURCHASE_ORDER', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SUPPLIER', 'Pending Supplier Approval'), ('CONFIRMED', 'Confirmed by Supplier'), ('IN_TRANSIT', 'In Transit / Shipped'), ('DELIVERED', 'Delivered & Received'), ('CANCELLED', 'Cancelled')], default='PENDING_SUPPLIER', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('expected_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_placed', to='accounts.company')),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders_received', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(default=1)),
                ('quantity_received', models.IntegerField(default=0)),
                ('agreed_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='e.g. 20.00 for 20% VAT', max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.purchaseorder')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
