# Generated by Django 5.2.3 on 2026-08-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completeness_score',
            field=models.FloatField(default=100.0, verbose_name='Order Completeness (W2)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='evaluation_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price_consistency_score',
            field=models.FloatField(default=100.0, verbose_name='Price Consistency (W3)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='timeliness_score',
            field=models.FloatField(default=100.0, verbose_name='Delivery Timeliness (W1)'),
        ),
    ]
