# Generated by Django 5.2.3 on 2026-08-18 00:50

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchaseorder_completeness_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(default=apps.orders.models.get_default_delivery_date),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SUPPLIER', 'Pending Supplier Approval'), ('CONFIRMED', 'Confirmed by Supplier'), ('IN_TRANSIT', 'In Transit / Shipped'), ('DELIVERED', 'Delivered & Received'), ('REJECTED', 'Rejected by Buyer'), ('CANCELLED', 'Cancelled')], default='PENDING_SUPPLIER', max_length=30),
        ),
    ]
