# Generated by Django 5.2.3 on 2026-08-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_purchaseorder_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SUPPLIER', 'Pending Supplier Approval'), ('CONFIRMED', 'Confirmed by Supplier'), ('IN_TRANSIT', 'In Transit / Shipped'), ('DELIVERED', 'Delivered & Received'), ('REJECTED_BY_SUPPLIER', 'Declined by Supplier'), ('REJECTED_BY_BUYER', 'Rejected by Buyer'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_SUPPLIER', max_length=30),
        ),
    ]
