# Generated by Django 5.2.3 on 2026-08-16 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w1_timeliness', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Weight 1: Delivery Timeliness')),
                ('w2_completeness', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Weight 2: Order Completeness')),
                ('w3_price_consistency', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Weight 3: Price Consistency')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sme_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_timeliness_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order_completeness_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price_consistency_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1 - Gold (Preferred)'), ('TIER_2', 'Tier 2 - Silver (Reliable)'), ('TIER_3', 'Tier 3 - Bronze (Needs Improvement)'), ('TIER_4', 'Tier 4 - Restricted (High Risk)')], default='TIER_1', max_length=20)),
                ('total_orders_evaluated', models.IntegerField(default=0)),
                ('on_time_orders_count', models.IntegerField(default=0)),
                ('delayed_orders_count', models.IntegerField(default=0)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('sme_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='accounts.company')),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='accounts.company')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('sme_company', 'supplier_company')},
            },
        ),
    ]
