# Generated by Django 5.2.3 on 2026-08-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='Units', help_text='e.g. Units, Boxes, Kg, Liters, Pallets', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('preferred_supplier', models.ForeignKey(blank=True, limit_choices_to={'company_type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('critical_threshold', models.IntegerField(default=20, help_text='Triggers critical stock alert if current stock <= threshold')),
                ('reorder_quantity', models.IntegerField(default=100, help_text='Standard replenishment quantity')),
                ('warehouse_location', models.CharField(blank=True, default='Main Warehouse - Bay A', max_length=100)),
                ('last_restocked_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='inventory.product')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('company', 'product')},
            },
        ),
    ]
