# Generated by Django 5.2.3 on 2026-08-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier-specific selling price', max_digits=12, null=True),
        ),
    ]
